HALF_STR_BUF_SIZE           = 21
FLOAT_STR_BUF_SIZE          = 41
DOUBLE_STR_BUF_SIZE         = 311
SCIENTIFIC_STR_BUF_SIZE     = 14
INT_STR_BUF_SIZE            = 12
LONG_STR_BUF_SIZE           = 21
UINT_STR_BUF_SIZE           = 11
ULONG_STR_BUF_SIZE          = 21